tactician:
    default_bus: query
    commandbus:
        query:
            method_inflector: tactician.handler.method_name_inflector.invoke
            middleware:
                - tactician.commandbus.query.middleware.command_handler
        command:
            method_inflector: tactician.handler.method_name_inflector.handle
            middleware:
                - tactician.commandbus.command.middleware.command_handler