security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    user_provider:
      id: App\Security\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: user_provider
      form_login:
        login_path: login
        check_path: login

    secured_area:
      form_login:
        enable_csrf: true

  access_control:
    - { path: ^/question, roles: ROLE_ADMIN }
