services:
  LearnByTests\Domain\Command\AddQuestionHandler:
    class: LearnByTests\Domain\Command\AddQuestionHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\AddQuestion, bus: command }

  LearnByTests\Domain\Command\AddAnswerHandler:
    class: LearnByTests\Domain\Command\AddAnswerHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\AddAnswer, bus: command }

  LearnByTests\Domain\Command\SetAnswerAsCorrectHandler:
    class: LearnByTests\Domain\Command\SetAnswerAsCorrectHandler
    arguments:
      - '@LearnByTests\Domain\Answer\AnswerRepository'
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\SetAnswerAsCorrect, bus: command }

  LearnByTests\Domain\Command\DeleteQuestionHandler:
    class: LearnByTests\Domain\Command\DeleteQuestionHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionPersister'
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\DeleteQuestion, bus: command }
