services:
  LearnByTests\Domain\Command\CreateQuestionHandler:
    class: LearnByTests\Domain\Command\CreateQuestionHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\CreateQuestion, bus: command }

  LearnByTests\Domain\Command\CreateAnswerHandler:
    class: LearnByTests\Domain\Command\CreateAnswerHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\CreateAnswer, bus: command }

  LearnByTests\Domain\Command\SetAnswerAsCorrectHandler:
    class: LearnByTests\Domain\Command\SetAnswerAsCorrectHandler
    arguments:
      - '@LearnByTests\Domain\Answer\AnswerRepository'
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\SetAnswerAsCorrect, bus: command }

  LearnByTests\Domain\Command\DeleteQuestionHandler:
    class: LearnByTests\Domain\Command\DeleteQuestionHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionPersister'
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\DeleteQuestion, bus: command }

  LearnByTests\Domain\Command\DeleteAnswerHandler:
    class: LearnByTests\Domain\Command\DeleteAnswerHandler
    arguments:
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\DeleteAnswer, bus: command }

  LearnByTests\Domain\Command\UpdateQuestionHandler:
    class: LearnByTests\Domain\Command\UpdateQuestionHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
      - '@LearnByTests\Domain\Question\QuestionPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\UpdateQuestion, bus: command }

  LearnByTests\Domain\Command\UpdateAnswerHandler:
    class: LearnByTests\Domain\Command\UpdateAnswerHandler
    arguments:
      - '@LearnByTests\Domain\Answer\AnswerRepository'
      - '@LearnByTests\Domain\Answer\AnswerPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\UpdateAnswer, bus: command }

  LearnByTests\Domain\Command\RegisterUserHandler:
    class: LearnByTests\Domain\Command\RegisterUserHandler
    arguments:
      - '@security.user_password_hasher'
      - '@LearnByTests\Domain\User\UserPersister'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Command\RegisterUser, bus: command }
