services:
  App\Controller\LoginController:
    class: App\Controller\LoginController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]

  App\Controller\RegistrationController:
    class: App\Controller\RegistrationController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]

  App\Controller\UserController:
    class: App\Controller\UserController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]

  App\Controller\AdminController:
    class: App\Controller\AdminController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]

  App\Controller\SuperAdminController:
    class: App\Controller\SuperAdminController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]