services:
  App\Form\Question\QuestionForm:
    class: App\Form\Question\QuestionForm
    tags: [ 'form.type' ]

  App\Form\Question\AnswerForm:
    class: App\Form\Question\AnswerForm
    tags: [ 'form.type' ]

  App\Form\Question\CorrectAnswerForm:
    class: App\Form\Question\CorrectAnswerForm
    tags: [ 'form.type' ]

  App\Form\RegisterUserForm:
    class: App\Form\RegisterUserForm
    tags: [ 'form.type' ]
