services:
  LearnByTests\Domain\Question\QuestionPersister:
    alias: LearnByTests\Infrastructure\Question\QuestionPersister

  LearnByTests\Domain\Answer\AnswerPersister:
    alias: LearnByTests\Infrastructure\Answer\AnswerPersister

  LearnByTests\Domain\User\UserPersister:
    alias: LearnByTests\Infrastructure\User\UserPersister

  LearnByTests\Domain\UserQuestionAnswer\UserQuestionAnswerPersister:
    alias: LearnByTests\Infrastructure\UserQuestionAnswer\UserQuestionAnswerPersister

  LearnByTests\Domain\UserSkippedQuestion\UserSkippedQuestionPersister:
    alias: LearnByTests\Infrastructure\UserSkippedQuestion\UserSkippedQuestionPersister