services:
  LearnByTests\Domain\Query\GetQuestionWithAnswersHandler:
    class: LearnByTests\Domain\Query\GetQuestionWithAnswersHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
      - '@LearnByTests\Domain\Answer\AnswerRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetQuestionWithAnswers, bus: query }

  LearnByTests\Domain\Query\GetQuestionsHandler:
    class: LearnByTests\Domain\Query\GetQuestionsHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetQuestions, bus: query }

  LearnByTests\Domain\Query\GetAnswerCountForQuestionHandler:
    class: LearnByTests\Domain\Query\GetAnswerCountForQuestionHandler
    arguments:
      - '@LearnByTests\Domain\Answer\AnswerRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetAnswerCountForQuestion, bus: query }
