services:
  LearnByTests\Domain\Query\GetQuestionWithAnswersHandler:
    class: LearnByTests\Domain\Query\GetQuestionWithAnswersHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
      - '@LearnByTests\Domain\Answer\AnswerRepository'
      - '@LearnByTests\Domain\UserSkippedQuestion\UserSkippedQuestionRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetQuestionWithAnswers, bus: query }

  LearnByTests\Domain\Query\FindQuestionsHandler:
    class: LearnByTests\Domain\Query\FindQuestionsHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\FindQuestions, bus: query }

  LearnByTests\Domain\Query\GetAnswerCountForQuestionHandler:
    class: LearnByTests\Domain\Query\GetAnswerCountForQuestionHandler
    arguments:
      - '@LearnByTests\Domain\Answer\AnswerRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetAnswerCountForQuestion, bus: query }

  LearnByTests\Domain\Query\GetCategoriesHandler:
    class: LearnByTests\Domain\Query\GetCategoriesHandler
    arguments:
      - '@LearnByTests\Domain\Category\CategoryRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetCategories, bus: query }

  LearnByTests\Domain\Query\GetSubCategoriesHandler:
    class: LearnByTests\Domain\Query\GetSubCategoriesHandler
    arguments:
      - '@LearnByTests\Domain\Category\CategoryRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetSubCategories, bus: query }

  LearnByTests\Domain\Query\GetUsersHandler:
    class: LearnByTests\Domain\Query\GetUsersHandler
    arguments:
      - '@LearnByTests\Domain\User\UserRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\GetUsers, bus: query }

  LearnByTests\Domain\Query\UnderDevHandler:
    class: LearnByTests\Domain\Query\UnderDevHandler
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\UnderDev, bus: query }

  LearnByTests\Domain\Query\FindQuestionForTestHandler:
    class: LearnByTests\Domain\Query\FindQuestionForTestHandler
    arguments:
      - '@LearnByTests\Domain\Question\QuestionRepository'
      - '@LearnByTests\Domain\UserQuestionAnswer\UserQuestionAnswerRepository'
      - '@LearnByTests\Domain\UserSkippedQuestion\UserSkippedQuestionRepository'
    tags:
      - { name: tactician.handler, command: LearnByTests\Domain\Query\FindQuestionForTest, bus: query }