services:
  LearnByTests\Domain\Question\QuestionRepository:
    alias: LearnByTests\Infrastructure\Question\QuestionRepository

  LearnByTests\Domain\Answer\AnswerRepository:
    alias: LearnByTests\Infrastructure\Answer\AnswerRepository

  LearnByTests\Domain\User\UserRepository:
    alias: LearnByTests\Infrastructure\User\UserRepository

  LearnByTests\Domain\Category\CategoryRepository:
    alias: LearnByTests\Infrastructure\Category\CategoryRepository