index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

question_add:
    path: /question/add
    controller: App\Controller\QuestionController::addQuestion
    methods: [ GET, POST ]

question_add_answer:
    path: /question/{questionId}/answer/add
    controller: App\Controller\QuestionController::addQuestionAnswer
    methods: [ GET, POST ]

question_select_correct_answer:
    path: /question/{questionId}/answers/select_correct
    controller: App\Controller\QuestionController::questionSelectCorrectAnswer
    methods: [ GET, POST ]

question_list:
    path: /questions
    controller: App\Controller\QuestionController::questionList
    methods: [ GET ]

question_details:
    path: /question/{questionId}/details
    controller: App\Controller\QuestionController::questionDetails
    methods: [ GET ]

question_delete:
    path: /question/{questionId}/delete
    controller: App\Controller\QuestionController::deleteQuestion
    methods: [ GET ]

question_delete_answer:
    path: /question/{questionId}/answer/{answerId}/delete
    controller: App\Controller\QuestionController::deleteQuestionAnswer
    methods: [ GET ]
