index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

# AdminController
question_list:
    path: /admin/question/list
    controller: App\Controller\AdminController::questionList
    methods: [ GET ]

question_category_list:
    path: /admin/question/category/{category}/list
    controller: App\Controller\AdminController::questionList
    methods: [ GET ]

question_details:
    path: /admin/question/{questionId}/details
    controller: App\Controller\AdminController::questionDetails
    methods: [ GET ]

delete_question:
    path: /admin/question/{questionId}/delete
    controller: App\Controller\AdminController::deleteQuestion
    methods: [ GET ]

create_question:
    path: /admin/question/create
    controller: App\Controller\AdminController::createQuestion
    methods: [ GET, POST ]

create_answer:
    path: /admin/question/{questionId}/answer/create
    controller: App\Controller\AdminController::createAnswer
    methods: [ GET, POST ]

select_correct_answer:
    path: /admin/question/{questionId}/answers/select_correct
    controller: App\Controller\AdminController::selectCorrectAnswer
    methods: [ GET, POST ]

select_category:
    path: /admin/question/{questionId}/category/select
    controller: App\Controller\AdminController::selectCategory
    methods: [ GET, POST ]
# end of AdminController

question_delete_answer:
    path: /question/{questionId}/answer/{answerId}/delete
    controller: App\Controller\QuestionController::deleteQuestionAnswer
    methods: [ GET ]

set_answer_as_correct:
    path: /question/{questionId}/answer/{answerId}/set_as_correct
    controller: App\Controller\QuestionController::setAnswerAsCorrect
    methods: [ GET ]

question_edit:
    path: /question/{questionId}/edit
    controller: App\Controller\QuestionController::editQuestion
    methods: [ GET, POST ]

question_answer_edit:
    path: /question/{questionId}/answer/{answerId}/edit
    controller: App\Controller\QuestionController::editQuestionAnswer
    methods: [ GET, POST ]

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [ GET, POST ]

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [ GET, POST ]

register_info:
    path: /register/info
    controller: App\Controller\RegistrationController::registerInfo
    methods: [ GET ]
