index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

question_add:
    path: /question/add
    controller: App\Controller\QuestionController::addQuestion
    methods: [ GET, POST ]

question_details:
    path: /question/{questionId}
    controller: App\Controller\QuestionController::questionDetails
    methods: [ GET ]

question_list:
    path: /questions
    controller: App\Controller\QuestionController::questionList
    methods: [ GET ]

select_valid_answer:
    path: /question/{questionId}/valid_answer
    controller: App\Controller\QuestionController::selectValidAnswer
    methods: [ GET, POST ]
