index:
    path: /
    controller: App\Controller\LoginController::login
    methods: [ GET ]

# AdminController
category_list:
    path: /admin/category/list
    controller: App\Controller\AdminController::categoryList
    methods: [ GET ]

question_list:
    path: /admin/{category}/question/list
    controller: App\Controller\AdminController::questionList
    methods: [ GET ]

question_category_list:
    path: /admin/{category}/category/{subcategory}/question/list
    controller: App\Controller\AdminController::questionList
    methods: [ GET ]

question_details:
    path: /admin/{category}/question/{questionId}/details
    controller: App\Controller\AdminController::questionDetails
    methods: [ GET ]

delete_question:
    path: /admin/{category}/question/{questionId}/delete
    controller: App\Controller\AdminController::deleteQuestion
    methods: [ GET ]

create_question:
    path: /admin/{category}/question/create
    controller: App\Controller\AdminController::createQuestion
    methods: [ GET, POST ]

create_answer:
    path: /admin/{category}/question/{questionId}/answer/create
    controller: App\Controller\AdminController::createAnswer
    methods: [ GET, POST ]

select_correct_answer:
    path: /admin/{category}/question/{questionId}/answers/select_correct
    controller: App\Controller\AdminController::selectCorrectAnswer
    methods: [ GET, POST ]

select_question_category:
    path: /admin/{category}/question/{questionId}/category/select
    controller: App\Controller\AdminController::selectQuestionCategory
    methods: [ GET, POST ]

update_question_category:
    path: /admin/{category}/question/{questionId}/category/update
    controller: App\Controller\AdminController::updateQuestionCategory
    methods: [ GET, POST ]

update_question:
    path: /admin/{category}/question/{questionId}/edit
    controller: App\Controller\AdminController::updateQuestion
    methods: [ GET, POST ]

set_answer_as_correct:
    path: /admin/{category}/question/{questionId}/answer/{answerId}/set_as_correct
    controller: App\Controller\AdminController::setAnswerAsCorrect
    methods: [ GET ]

update_answer:
    path: /admin/{category}/question/{questionId}/answer/{answerId}/edit
    controller: App\Controller\AdminController::updateAnswer
    methods: [ GET, POST ]

add_answer:
    path: /admin/{category}/question/{questionId}/answer/add
    controller: App\Controller\AdminController::addAnswer
    methods: [ GET, POST ]

delete_answer:
    path: /admin/{category}/question/{questionId}/answer/{answerId}/delete
    controller: App\Controller\AdminController::deleteAnswer
    methods: [ GET ]

duplicate_question:
    path: /admin/{category}/question/{questionId}/duplicate
    controller: App\Controller\AdminController::duplicateQuestion
    methods: [ GET ]
# end of AdminController

# SuperAdminController
user_list:
    path: /super_admin/user/list
    controller: App\Controller\SuperAdminController::userList
    methods: [ GET ]

activate_user:
    path: /super_admin/user/{userId}/activate
    controller: App\Controller\SuperAdminController::activateUser
    methods: [ GET ]

deactivate_user:
    path: /super_admin/user/{userId}/deactivate
    controller: App\Controller\SuperAdminController::deactivateUser
    methods: [ GET ]

delete_user:
    path: /super_admin/user/{userId}/delete
    controller: App\Controller\SuperAdminController::deleteUser
    methods: [ GET ]
# end of SuperAdminController

# UserController
user_category_list:
    path: /user/category/list
    controller: App\Controller\UserController::categoryList
    methods: [ GET ]

user_question_list:
    path: /user/{category}/question/list
    controller: App\Controller\UserController::questionList
    methods: [ GET ]

user_question_category_list:
    path: /user/{category}/question/category/{subcategory}/list
    controller: App\Controller\UserController::questionCategoryList
    methods: [ GET ]

user_question_details:
    path: /user/{category}/question/{questionId}/details
    controller: App\Controller\UserController::questionDetails
    methods: [ GET ]

user_delete_all_question_answers:
    path: /user/{category}/answers/delete
    controller: App\Controller\UserController::deleteUserQuestionAnswers
    methods: [ GET ]

user_delete_question_answers:
    path: /user/{category}/category/{subcategory}/answers/delete
    controller: App\Controller\UserController::deleteUserQuestionAnswers
    methods: [ GET ]

all_categories_test:
    path: /user/{category}/question/{questionId}/test
    controller: App\Controller\UserController::allCategoriesTest
    methods: [ GET, POST ]

category_test:
    path: /user/{category}/category/{subcategory}/question/{questionId}/test
    controller: App\Controller\UserController::singleCategoryTest
    methods: [ GET, POST ]

skip_question:
    path: /user/question/{questionId}/skip
    controller: App\Controller\UserController::toggleSkipQuestion
    methods: [ GET ]

unskip_question:
    path: /user/question/{questionId}/unskip
    controller: App\Controller\UserController::toggleSkipQuestion
    methods: [ GET ]
# end of UserController

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [ GET, POST ]

logout:
    path: /logout
    methods: [ GET ]

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [ GET, POST ]

register_info:
    path: /register/info
    controller: App\Controller\RegistrationController::registerInfo
    methods: [ GET ]
