index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

add_question:
    path: /question/add
    controller: App\Controller\QuestionController::add
    methods: [ GET, POST ]
