index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

question_add:
    path: /question/add
    controller: App\Controller\QuestionController::addQuestion
    methods: [ GET, POST ]

question_add_answer:
    path: /question/{questionId}/answer/add
    controller: App\Controller\QuestionController::addQuestionAnswer
    methods: [ GET, POST ]

question_select_correct_answer:
    path: /question/{questionId}/answers/select_correct
    controller: App\Controller\QuestionController::questionSelectCorrectAnswer
    methods: [ GET, POST ]

question_list:
    path: /questions
    controller: App\Controller\QuestionController::questionList
    methods: [ GET ]

question_category_list:
    path: /questions/category/{category}
    controller: App\Controller\QuestionController::questionList
    methods: [ GET ]

question_details:
    path: /question/{questionId}/details
    controller: App\Controller\QuestionController::questionDetails
    methods: [ GET ]

question_delete:
    path: /question/{questionId}/delete
    controller: App\Controller\QuestionController::deleteQuestion
    methods: [ GET ]

question_delete_answer:
    path: /question/{questionId}/answer/{answerId}/delete
    controller: App\Controller\QuestionController::deleteQuestionAnswer
    methods: [ GET ]

set_answer_as_correct:
    path: /question/{questionId}/answer/{answerId}/set_as_correct
    controller: App\Controller\QuestionController::setAnswerAsCorrect
    methods: [ GET ]

question_edit:
    path: /question/{questionId}/edit
    controller: App\Controller\QuestionController::editQuestion
    methods: [ GET, POST ]

question_answer_edit:
    path: /question/{questionId}/answer/{answerId}/edit
    controller: App\Controller\QuestionController::editQuestionAnswer
    methods: [ GET, POST ]

question_select_category:
    path: /question/{questionId}/select_category
    controller: App\Controller\QuestionController::selectQuestionCategory
    methods: [ GET, POST ]

