index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

# AdminController
category_list:
    path: /admin/category/list
    controller: App\Controller\AdminController::categoryList
    methods: [ GET ]

question_list:
    path: /{category}/admin/question/list
    controller: App\Controller\AdminController::questionList
    methods: [ GET ]

question_category_list:
    path: /{category}/admin/question/category/{subcategory}/list
    controller: App\Controller\AdminController::questionList
    methods: [ GET ]

question_details:
    path: /{category}/admin/question/{questionId}/details
    controller: App\Controller\AdminController::questionDetails
    methods: [ GET ]

delete_question:
    path: /{category}/admin/question/{questionId}/delete
    controller: App\Controller\AdminController::deleteQuestion
    methods: [ GET ]

create_question:
    path: /{category}/admin/question/create
    controller: App\Controller\AdminController::createQuestion
    methods: [ GET, POST ]

create_answer:
    path: /{category}/admin/question/{questionId}/answer/create
    controller: App\Controller\AdminController::createAnswer
    methods: [ GET, POST ]

select_correct_answer:
    path: /{category}/admin/question/{questionId}/answers/select_correct
    controller: App\Controller\AdminController::selectCorrectAnswer
    methods: [ GET, POST ]

select_question_category:
    path: /{category}/admin/question/{questionId}/category/select
    controller: App\Controller\AdminController::selectQuestionCategory
    methods: [ GET, POST ]

update_question_category:
    path: /{category}/admin/question/{questionId}/category/update
    controller: App\Controller\AdminController::updateQuestionCategory
    methods: [ GET, POST ]

update_question:
    path: /{category}/admin/question/{questionId}/edit
    controller: App\Controller\AdminController::updateQuestion
    methods: [ GET, POST ]

set_answer_as_correct:
    path: /{category}/admin/question/{questionId}/answer/{answerId}/set_as_correct
    controller: App\Controller\AdminController::setAnswerAsCorrect
    methods: [ GET ]

update_answer:
    path: /{category}/admin/question/{questionId}/answer/{answerId}/edit
    controller: App\Controller\AdminController::updateAnswer
    methods: [ GET, POST ]

add_answer:
    path: /{category}/admin/question/{questionId}/answer/add
    controller: App\Controller\AdminController::addAnswer
    methods: [ GET, POST ]

delete_answer:
    path: /{category}/admin/question/{questionId}/answer/{answerId}/delete
    controller: App\Controller\AdminController::deleteAnswer
    methods: [ GET ]

duplicate_question:
    path: /{category}/admin/question/{questionId}/duplicate
    controller: App\Controller\AdminController::duplicateQuestion
    methods: [ GET ]
# end of AdminController


login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [ GET, POST ]

logout:
    path: /logout
    methods: [ GET ]

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [ GET, POST ]

register_info:
    path: /register/info
    controller: App\Controller\RegistrationController::registerInfo
    methods: [ GET ]
