services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\QueryBus\QueryBus:
        alias: LearnByTests\Infrastructure\Tactician\QueryBus

    App\CommandBus\CommandBus:
        alias: LearnByTests\Infrastructure\Tactician\CommandBus

    App\Twig\QuillDeltaParser:
        class: App\Twig\QuillDeltaParser
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Twig\TrimWords:
        class: App\Twig\TrimWords
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Security\UserProvider:
        class: App\Security\UserProvider
        arguments:
            - '@LearnByTests\Domain\User\UserRepository'

imports:
    - { resource: 'infrastructure/services.yaml' }
    - { resource: 'cli_commands.yaml' }
    - { resource: 'repositories.yaml' }
    - { resource: 'controllers.yaml' }
    - { resource: 'persisters.yaml' }
    - { resource: 'commands.yaml' }
    - { resource: 'queries.yaml' }
    - { resource: 'forms.yaml' }
