parameters:
  learn_by_tests.mysql_host: mysql
  learn_by_tests.mysql_port: 3306
  learn_by_tests.mysql_database: learn_by_tests
  learn_by_tests.mysql_user: learn_by_tests
  learn_by_tests.mysql_password: password123
